version: '2'

services:
  gramine-jvm:
    image: mboettger/gramine-jvm:latest
    container_name: "gramine-jvm"
    build: .
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
